env:
  node: true
  es6: true
  browser: true
  es2021: true
extends:
  - 'standard'
  - 'eslint:recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - standard
rules: {
  no-unused-vars: 1,
  new-cap: 0,
  space-before-function-paren: 0,
  comma-dangle: 0
}
